package example

// Code generated by "bitfield -type=Flags,Tiny,Wide,Color,padded -output ./generated.go"; DO NOT EDIT.

// Pack returns the bit-packed uint16 representation of v.
func (v Flags) Pack() uint16 {
	var out uint16
	out |= uint16(v.Opcode & 0x3f)
	out |= uint16(v.Mode&0x3) << 6
	if v.Enabled {
		out |= 1 << 8
	}
	out |= uint16(v.Rsvd&0x7f) << 9
	return out
}

// Unpack decodes a packed uint16 into a Flags.
func (v *Flags) Unpack(raw uint16) {
	*v = Flags{
		Opcode:  uint8(raw & 0x3f),
		Mode:    uint8(raw >> 6 & 0x3),
		Enabled: raw>>8&1 != 0,
		Rsvd:    uint8(raw >> 9 & 0x7f),
	}
}

// Pack returns the bit-packed uint8 representation of v.
func (v Tiny) Pack() uint8 {
	var out uint8
	if v.A {
		out |= 1
	}
	out |= uint8(v.B&0x7) << 1
	if v.C {
		out |= 1 << 7
	}
	return out
}

// Unpack decodes a packed uint8 into a Tiny.
func (v *Tiny) Unpack(raw uint8) {
	*v = Tiny{
		A: raw&1 != 0,
		B: u3(raw >> 1 & 0x7),
		C: raw>>7&1 != 0,
	}
}

// Pack returns the bit-packed uint64 representation of v.
func (v Wide) Pack() uint64 {
	var out uint64
	out |= uint64(v.Lo)
	out |= uint64(v.Hi) << 32
	return out
}

// Unpack decodes a packed uint64 into a Wide.
func (v *Wide) Unpack(raw uint64) {
	*v = Wide{
		Lo: uint32(raw),
		Hi: uint32(raw >> 32),
	}
}

// Pack returns the bit-packed uint16 representation of v.
func (v Color) Pack() uint16 {
	var out uint16
	out |= uint16(v.R&0x7) << 1
	out |= uint16(v.G&0x7) << 5
	out |= uint16(v.B&0x7) << 9
	return out
}

// Unpack decodes a packed uint16 into a Color.
func (v *Color) Unpack(raw uint16) {
	*v = Color{
		R: uint8(raw >> 1 & 0x7),
		G: uint8(raw >> 5 & 0x7),
		B: uint8(raw >> 9 & 0x7),
	}
}

// pack returns the bit-packed uint8 representation of v.
func (v padded) pack() uint8 {
	var out uint8
	out |= v.lo & 0xf
	out |= (v.hi & 0x1) << 6
	if v.set {
		out |= 1 << 7
	}
	return out
}

// unpack decodes a packed uint8 into a padded.
func (v *padded) unpack(raw uint8) {
	*v = padded{
		lo:  raw & 0xf,
		hi:  raw >> 6 & 0x1,
		set: raw>>7&1 != 0,
	}
}
