package example

// Code generated by "bitfield -type=Flags,Tiny,Wide -output ./generated.go"; DO NOT EDIT.

// Flags bit layout (LSB first), total 16 bits in uint16:
//
//	[ 0.. 5] Opcode (uint8, 6 bits)
//	[ 6.. 7] Mode (uint8, 2 bits)
//	[ 8    ] Enabled (bool)
//	[ 9..15] Rsvd (uint8, 7 bits)
//
// Pack returns the bit-packed uint16 representation of v.
func (v Flags) Pack() uint16 {
	var out uint16
	out |= uint16(v.Opcode & 0x3f)
	out |= uint16(v.Mode&0x3) << 6
	if v.Enabled {
		out |= 1 << 8
	}
	out |= uint16(v.Rsvd&0x7f) << 9
	return out
}

// UnpackFlags decodes a packed uint16 into a Flags.
func UnpackFlags(raw uint16) Flags {
	return Flags{
		Opcode:  uint8(raw & 0x3f),
		Mode:    uint8(raw >> 6 & 0x3),
		Enabled: raw>>8&1 != 0,
		Rsvd:    uint8(raw >> 9 & 0x7f),
	}
}

// Tiny bit layout (LSB first), total 5 bits in uint8:
//
//	[ 0    ] A (bool)
//	[ 1.. 3] B (uint8, 3 bits)
//	[ 4    ] C (bool)
//
// Pack returns the bit-packed uint8 representation of v.
func (v Tiny) Pack() uint8 {
	var out uint8
	if v.A {
		out |= 1
	}
	out |= (v.B & 0x7) << 1
	if v.C {
		out |= 1 << 4
	}
	return out
}

// UnpackTiny decodes a packed uint8 into a Tiny.
func UnpackTiny(raw uint8) Tiny {
	return Tiny{
		A: raw&1 != 0,
		B: raw >> 1 & 0x7,
		C: raw>>4&1 != 0,
	}
}

// Wide bit layout (LSB first), total 64 bits in uint64:
//
//	[ 0..31] Lo (uint32, 32 bits)
//	[32..63] Hi (uint32, 32 bits)
//
// Pack returns the bit-packed uint64 representation of v.
func (v Wide) Pack() uint64 {
	var out uint64
	out |= uint64(v.Lo)
	out |= uint64(v.Hi) << 32
	return out
}

// UnpackWide decodes a packed uint64 into a Wide.
func UnpackWide(raw uint64) Wide {
	return Wide{
		Lo: uint32(raw),
		Hi: uint32(raw >> 32),
	}
}
