package mypkg

// Code generated by github.com/arl/bitfield. DO NOT EDIT.

type Scroll uint16

func (s Scroll) X() uint8 {
	return uint8(s & 0x1f)
}

func (s *Scroll) SetX(val uint8) {
	*s &^= 0x1f
	*s |= Scroll(val & 0x1f)
}

func (s Scroll) Y() uint8 {
	return uint8((s >> 5) & 0x1f)
}

func (s *Scroll) SetY(val uint8) {
	*s &^= 0x1f << 5
	*s |= Scroll(val&0x1f) << 5
}
