package testpkg

// Code generated by /tmp/go-build738358689/b001/exe/main -in testpkg/mystruct.go. DO NOT EDIT.

type MyStruct uint16

func (s MyStruct) Low() uint8 {
	return uint8(s & 0xff)
}

func (s MyStruct) SetLow(val uint8) MyStruct {
	return s&^0xff | MyStruct(val&0xff)
}

func (s MyStruct) High() uint8 {
	return uint8((s >> 8) & 0x7f)
}

func (s MyStruct) SetHigh(val uint8) MyStruct {
	return s&^(0x7f<<8) | (MyStruct(val&0x7f) << 8)
}

func (s MyStruct) CoarseX() uint8 {
	return uint8(s & 0x1f)
}

func (s MyStruct) SetCoarseX(val uint8) MyStruct {
	return s&^0x1f | MyStruct(val&0x1f)
}

func (s MyStruct) CoarseY() uint8 {
	return uint8((s >> 5) & 0x1f)
}

func (s MyStruct) SetCoarseY(val uint8) MyStruct {
	return s&^(0x1f<<5) | (MyStruct(val&0x1f) << 5)
}

func (s MyStruct) NametableX() uint8 {
	return uint8((s >> 10) & 0x1)
}

func (s MyStruct) SetNametableX(val uint8) MyStruct {
	return s&^(0x1<<10) | (MyStruct(val&0x1) << 10)
}

func (s MyStruct) NametableY() uint8 {
	return uint8((s >> 11) & 0x1)
}

func (s MyStruct) SetNametableY(val uint8) MyStruct {
	return s&^(0x1<<11) | (MyStruct(val&0x1) << 11)
}

func (s MyStruct) FineY() uint8 {
	return uint8((s >> 12) & 0x7)
}

func (s MyStruct) SetFineY(val uint8) MyStruct {
	return s&^(0x7<<12) | (MyStruct(val&0x7) << 12)
}
